/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 91975
 */
public class Dashboard extends javax.swing.JDialog {

        /**
         * Creates new form Edit_Info
         */
        public Dashboard(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                addmember = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                search = new javax.swing.JButton();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                Editmember = new javax.swing.JButton();
                searchingname = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                Table1 = new javax.swing.JTable();
                newmember = new javax.swing.JButton();
                reset = new javax.swing.JButton();

                addmember.setBackground(new java.awt.Color(153, 0, 153));
                addmember.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
                addmember.setForeground(new java.awt.Color(255, 255, 255));
                addmember.setText("Add Member ");
                addmember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                addmember.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addmemberActionPerformed(evt);
                        }

                        private void addmemberActionPerformed(ActionEvent evt) {
                        }
                });

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                jPanel1.setForeground(new java.awt.Color(204, 0, 204));

                jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(51, 51, 51));
                jLabel1.setText("Address");

                jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 2, 36)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(204, 0, 204));
                jLabel2.setText("Book ");

                search.setBackground(new java.awt.Color(153, 0, 153));
                search.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
                search.setForeground(new java.awt.Color(255, 255, 255));
                search.setText("Click Here");
                search.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                search.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel3.setText("-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");

                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundPhoto1.png"))); // NOI18N

                Editmember.setBackground(new java.awt.Color(153, 0, 153));
                Editmember.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
                Editmember.setForeground(new java.awt.Color(255, 255, 255));
                Editmember.setText("Edit Member ");
                Editmember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                Editmember.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                EditmemberActionPerformed(evt);
                        }
                });

                Table1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Member_ID", "Name", "Job Description"
                                }) {
                        Class[] types = new Class[] {
                                        java.lang.Integer.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean[] {
                                        false, true, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit[columnIndex];
                        }
                });
                jScrollPane1.setViewportView(Table1);

                newmember.setBackground(new java.awt.Color(153, 0, 153));
                newmember.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
                newmember.setForeground(new java.awt.Color(255, 255, 255));
                newmember.setText("Add Member ");
                newmember.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                newmember.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                newmemberActionPerformed(evt);
                        }
                });

                reset.setBackground(new java.awt.Color(153, 0, 153));
                reset.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
                reset.setForeground(new java.awt.Color(255, 255, 255));
                reset.setText("Reset");
                reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                reset.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                resetActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(88, 88, 88)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                141,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(newmember,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                177,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Editmember,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                177,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(74, 74, 74))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGap(99, 99, 99)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                519,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(searchingname,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                210,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel4,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                0,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addGap(73, 73, 73))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addComponent(search,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                125,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(448, 448,
                                                                                                                                448))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(reset,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                125,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(598, 598, 598)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(62, 62, 62)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(Editmember)
                                                                                .addComponent(newmember))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel3)
                                                                .addGap(16, 16, 16)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(search,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                41,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(searchingname,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                41,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                100, Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(jLabel4,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                347,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                0, Short.MAX_VALUE))
                                                                .addGap(43, 43, 43)
                                                                .addComponent(reset,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(77, 77, 77)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(24, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(26, 26, 26)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(28, Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void newmemberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newmemberActionPerformed
                New_Info ni = new New_Info();
                dispose();
        }// GEN-LAST:event_newmemberActionPerformed

        private void EditmemberActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addmemberActionPerformed
                Edit_Info ei = new Edit_Info();
                dispose();
        }// GEN-LAST:event_addmemberActionPerformed

        private void searchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchActionPerformed
                if (searchingname.getText().equals(null)) {
                        try {
                                Class.forName("com.mysql.cj.jdbc.Driver");
                                Connection con = DriverManager.getConnection(
                                                "jdbc:mysql://localhost:3306/Address_Book", "root",
                                                "2412");
                                // String query = "Select S_no , Name , Job_Description from member_detail where
                                // "
                                // + "Name = " + name;
                                String query2 = "";
                                PreparedStatement pst = con.prepareStatement(query2);
                                ResultSet r = pst.executeQuery(query2);
                                while (r.next()) {
                                        String S_no = r.getString(1);
                                        String Name = r.getString(2);
                                        String Job_Description = r.getString(3);
                                        String tb[] = { S_no, Name, Job_Description
                                        };
                                        DefaultTableModel tbm = (DefaultTableModel) Table1.getModel();
                                        tbm.addRow(tb);
                                        JOptionPane.showMessageDialog(null, "Searching Successfull");
                                }
                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e, null, 0);
                        }
                }
                // String name = searchingname.getText();
                else {
                        try {
                                Class.forName("com.mysql.cj.jdbc.Driver");
                                Connection con = DriverManager.getConnection(
                                                "jdbc:mysql://localhost:3306/Address_Book", "root",
                                                "2412");
                                // String query = "Select S_no , Name , Job_Description from member_detail where
                                // "
                                // + "Name = " + name;
                                String query2 = "Select S_no, name, job_description from member_detail";
                                PreparedStatement pst = con.prepareStatement(query2);
                                ResultSet r = pst.executeQuery(query2);
                                while (r.next()) {
                                        String S_no = r.getString(1);
                                        String Name = r.getString(2);
                                        String Job_Description = r.getString(3);
                                        String tb[] = { S_no, Name, Job_Description
                                        };
                                        DefaultTableModel tbm = (DefaultTableModel) Table1.getModel();
                                        tbm.addRow(tb);

                                }
                        } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, e, null, 0);
                        }
                }
        }// GEN-LAST:event_searchActionPerformed

        private DefaultTableModel getModel() {
                return null;
        }

        private void resetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_search1ActionPerformed
                searchingname.setText(null);
                ((DefaultTableModel) Table1.getModel()).setNumRows(0);

        }// GEN-LAST:event_search1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public Dashboard() {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                Dashboard dialog = new Dashboard(new javax.swing.JFrame(), true);
                                dialog.setLocation(280, 90);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton Editmember;
        private javax.swing.JTable Table1;
        private javax.swing.JButton addmember;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton newmember;
        private javax.swing.JButton reset;
        private javax.swing.JButton search;
        private javax.swing.JTextField searchingname;
        // End of variables declaration//GEN-END:variables
}
